# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Renee Wrysinski
description: >- # this means to ignore newlines until "baseurl:"
  Renee Wrysinski's portfolio website.
domain: reneewrysinski.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://reneewrysinski.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
      dropdown:
        - name: Academic
        - name: Personal
    - name: Resume

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: reneewrysinski@gmail.com
      link: mailto:reneewrysinski@gmail.com
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/rwrysinski
    - name: GitHub
      link: http://github.com/reneewrysinski
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml

collections:
  projects:
    output: true
  academic:
    output: true
    permalink: /projects/academic/:title
    parent: projects
  academic-child-engi210:
    output: true
    permalink: /projects/academic/engi210/:title
    parent: academic
  personal:
    output: true
    permalink: /projects/personal/:title
    parent: projects
collections_dir: collections

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
